### PR TITLE
Prevent oversized emojis

### PR DESCRIPTION
**Pull request by cfxd**
Prevent oversized emojis in admin like this...

image

### CODE REVIEW

**Review by Lewiscowles1986 — CHANGES_REQUESTED** [review]
I need this to only change the one-line (for some reason there are white-space changes on other lines).

~Also could you submit as an issue so I can have a record of what causes.~

~Just something like "when I enter an inline emojii, if this plugin is not active I see {X}. After I see {Y}."~

I love how small it is and if you make ~those changes~ that change I can promise to merge. Thank you :+1: :smile_cat:

**Comment by cfxd** [comment]
Man, I didn't even notice those until you pointed them out. My IDE automatically removed those white spaces.

Is there a particular reason you want to keep them? Want them removed as another PR? I could also just change the issue/commit msg to include white space removal...

**Comment by Lewiscowles1986** [comment]
I did create the issue for you. Is there some way you can edit the commit using a text-editor (it's a one-file edit, notepad, gedit or any text editor should allow without meddling too much). 

I'd also prefer not to have a PR for whitespace removal :rofl:

**Comment by cfxd** [comment]
Yeah no problem, I just rebased removing the whitespace removal. Any particular reason you want to keep the whitespace?

**Review by Lewiscowles1986 — APPROVED** [review]

**Comment by Lewiscowles1986** [comment]
The main reason is that everyone could make changes based upon preference, or IDE config, leading to making merge conflicts harder to resolve (we're looking at lines we don't need to look at).

Thank you for being awesome btw :wink:

**Comment by cfxd** [comment]
Thanks :)

The white space really should be removed.

**Pull request merged**
